version: "2"

services:
  redis:
    image: redis:alpine
    container_name: streamers_redis
    ports:
      - "127.0.0.1:6381:6379"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
